//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raspisanie
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public string Statussss { get; set; }
        public string Statusssssss { get; set; }
        public string Stattttus { get; set; }
    }
}
